### ISSUE TITLE
Формирование окружения разработчика

### ISSUE THREAD

**Issue by alehinsasha** [Vovqa412/FinalTask#1]
- [ ] Внешние отчеты и обработки разбираются на исходники
- [ ] Структура каталогов репозитория из bootstrap

**Comment by alehinsasha** [comment]
Откройте issue, подзадачи не решены.

**Comment by Vovqa412** [comment]
Настроил структуру каталогов из bootstrap и precommit1c с помощью скрипта, удивился, что пустые каталоги не отобразились в веб версии гита
