### ISSUE TITLE
Программная работа с функциональностью "Автоматизированное тестирование 1С"

### ISSUE THREAD

**Issue by alehinsasha** [Vovqa412/FinalTask#4]
- [ ] Создать свой шаг проверяющий текст предупреждения

**Comment by Vovqa412** [comment]
@alehinsasha не могли бы уточнить про какой текст предупреждения идёт речь?

**Comment by alehinsasha** [comment]
Например: нажимаете кнопку, в обработчике события нажатия на эту кнопку вызывается метод `Предупреждение(` а в предприятия появляется окно с текстом предупреждения. Вот этот текст можно прочитать, т.е. создать свой шаг проверяющий текст предупреждения. Но можно и сообщения.

**Comment by alehinsasha** [comment]
**В дополнение к проверке навыка "Создать свой шаг проверяющий текст предупреждения"**

Нужно реализовать свой шаг используя функциональность "Автоматизированное тестирование 1С" и свойство "ТестовоПриложение" переменной "КонтекстСохраняемый", который проверяет сообщения пользователю в момент проведения документа реализации товара. Например, если нет в сообщении текста "Не хватает товара" то реализация провелясь корректно. Или если есть текст "Не хватает товара" а товара действительно нет на остатках, то - Ок, функциональность контроля остатков проверена.

**Comment by Vovqa412** [comment]
@alehinsasha в фиче по проверке реализации после нажатия на кнопку "Провести" добавил шаг, в котором разместил следующий код:
```Если КонтекстСохраняемый.Свойство("ТестовоПриложение") Тогда
		Сообщить(КонтекстСохраняемый.ТестовоПриложение);
КонецЕсли;
```
В конфигурации добавил предупреждение, пробовал и с сообщением, но ни в какую.

Если принудительно пихать в КонтекстСохраняемый оповещение, то далее получается его словить, но полагаю это не по фен шую. Подскажите, как правильно воспользоваться свойством "ТестовоПриложение"?

**Comment by alehinsasha** [comment]
1) Посмотрите в отладчике какой тип у свойства `ТестовоеПриложение`.
2) Найдите в синтакс-помощнике в блоке "Автоматизированное тестирование" метод для чтения с клиента тестирование сообщений пользователю.

Пишите, если будут вопросы, ничего такого в этом нет, вы учитесь)
