### ISSUE TITLE
Сообщить данные для получения сертификата финалиста

### ISSUE THREAD

**Issue by alehinsasha** [Vovqa412/FinalTask#6]
В комментарии к этому issue напишите ваши:

* Имя Фамилию (в дательном падеже)
* Адрес электронной почты, на которую выслать сертификат

**Comment by Vovqa412** [comment]
* Владимиру Тимошенко
* timoshenko@itehnik.ru

**Comment by alehinsasha** [comment]
Поздравительное письмо отправлено на указанный адрес! Прошу подтвердить получение.

**Comment by Vovqa412** [comment]
@alehinsasha поздравительное письмо получил.
